export const ProductsData = [
    {
        id: 1,
        product: 'Termo Stanley Blanco',
        categoria: "Termos",
        Precio: 32000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_968935-MLA40150117241_122019-O.webp',
        stock: 10,
        amount: 0,
        capacidad: "1,5 L",
        detalles: "Porque algunas cosas son para toda la vida, este termo Stanley fue pensado para acompañarte a través de los años, ya que durabilidad y estilo son las palabras que definen a la marca.",
    },
    {
        id: 2,
        product: 'Termo Stanley Negro',
        categoria: "Termos",
        Precio: 30000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_631197-MLA40974977558_032020-O.webp',
        stock: 20,
        amount: 0,
        capacidad: "1,5 L",
        detalles: "Porque algunas cosas son para toda la vida, este termo Stanley fue pensado para acompañarte a través de los años, ya que durabilidad y estilo son las palabras que definen a la marca.",
    },
    {
        id: 3,
        product: 'Termo Stanley Bordo',
        categoria: "Termos",
        Precio: 30000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_708840-MLA42454895076_072020-O.webp',
        stock: 6,
        amount: 0,
        capacidad: "1,5 L",
        detalles: "Porque algunas cosas son para toda la vida, este termo Stanley fue pensado para acompañarte a través de los años, ya que durabilidad y estilo son las palabras que definen a la marca.",
    },
    {
        id: 4,
        product: 'Termo Stanley Verde',
        categoria: "Termos",
        Precio: 28000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_961858-MLA40111899150_122019-O.webp',
        stock: 30,
        amount: 0,
        capacidad: "1,5 L",
        detalles: "Porque algunas cosas son para toda la vida, este termo Stanley fue pensado para acompañarte a través de los años, ya que durabilidad y estilo son las palabras que definen a la marca.",
    },
    {
        id: 5,
        product: 'Termo Stanley Edición Limitada',
        categoria: "Termos",
        Precio: 30000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_682419-MLA50028757104_052022-O.webp',
        stock: 5,
        amount: 0,
        capacidad: "1,5 L",
        detalles: "Porque algunas cosas son para toda la vida, este termo Stanley fue pensado para acompañarte a través de los años, ya que durabilidad y estilo son las palabras que definen a la marca.",
    },
    {
        id: 6,
        product: 'Termo Contigo',
        categoria: "Termos",
        Precio: 18000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_677944-MLA42682698324_072020-O.webp',
        stock: 50,
        amount: 0,
        capacidad: "1,5 L",
        detalles: "Termo de Acero inoxidable",
    },
    {
        id: 7,
        product: 'Termo Coleman',
        categoria: "Termos",
        Precio: 23000,
        img: 'https://http2.mlstatic.com/D_NQ_NP_911277-MLA45822032320_052021-O.webp',
        stock: 5,
        amount: 0,
        capacidad: "1,2 L",
        detalles: "Termo de Acero inoxidable",
    },
    {
        id:8 ,
        product: 'Mate Imperial cuero + bombilla de regalo',
        categoria: "Mates",
        Precio: 7699,
        img: 'https://http2.mlstatic.com/D_NQ_NP_702437-MLA48733352973_012022-O.webp',
        stock: 50,
        amount: 0,
        capacidad: "-",
        detalles: "Cuero 100% Vacuno y forrado en calabaza Natural de alto grosor, excelentes terminaciones.",
    },
    {
        id:9 ,
        product: 'Mate Pampa Uruguayo Camionero Termico + Bombilla',
        categoria: "Mates",
        Precio: 1799,
        img: 'https://http2.mlstatic.com/D_NQ_NP_649779-MLA49062471447_022022-O.webp',
        stock: 50,
        amount: 0,
        capacidad: "-",
        detalles: "Hecho de PVC, su forma y elegancia remite al mate de cuero consus correspondientes costudas",
    },
    {
        id:10 ,
        product: 'Mate imperial Alpaca premium bombilla Pico de Loro',
        categoria: "Mates",
        Precio: 11599,
        img: 'https://http2.mlstatic.com/D_NQ_NP_2X_668851-MLA51110697845_082022-F.webp',
        stock: 20,
        amount: 0,
        capacidad: "-",
        detalles: "Mate de cuero de vaca, la mejor calidad 3 mm. Calabaza premium de alto grosor",
    },
    {
        id:11 ,
        product: "Matte Combo Matero",
        categoria: "Combos",
        Precio: 10599,
        img: 'https://http2.mlstatic.com/D_NQ_NP_2X_851463-MLA49641551685_042022-F.webp',
        stock: 20,
        amount: 0,
        capacidad: "-",
        detalles: "Combo matero marca MATTE. Termo marca Waterdog. ",
    }
]; 